# Default values for nextflow-api.
# Declare variables to be passed into your templates.

# PVC
NewLocalPVC:
  # If true, create new PVC on local cluster.
  Enabled: false
  Name: nextflow-api-pvc
  StorageClass: nfs
  Size: 20Gi

ExistingLocalPVC:
  # If true, use existing PVC on local cluster.
  Enabled: true
  Name: ndn-pvc

Remote:
  # If true, use PVC/compute of remote cluster.
  # Otherwise, PVC/compute of local cluster will be used.
  # (temp, future will be dynamically configurable)
  Enabled: false
  Context: nautilus
  PVC: deepgtex-prp

# Web server deployment settings
WebServer:
  # Number of containers
  Replicas: 1
  # Resource requests and limits per container
  Resources:
    Requests:
      CPU: 3
      Memory: 10Gi
    Limits:
      CPU: 3
      Memory: 10Gi

# Load Balancer Settings
LoadBalancer:
  Enabled: true

# Ingress control settings
Ingress:
  # If true, use Ingress control.
  # Otherwise, generic LoadBalancer networking will be used,
  # and the other settings in this section will be ignored.
  Enabled: false
  # The subdomain to associate with this service.
  Host: nextflow-api-rel.nautilus.optiputer.net
  # The class of the ingress controller to use.
  # For SLATE this should be 'slate'.
  Class: traefik

# NodePort Settings
NodePorts:
  Enabled: false
  NodePort: 31376
